### ISSUE TITLE
Chance de cruzamento

### ISSUE THREAD

**Issue by joao-felipe-goncalves** [Ailtonjr/AG-Caixeiro-Viajante#13]
Implementar chance de cruzamento baseado no percentual informado pelo usuário.

**Comment by Ailtonjr** [comment]
Acredito já estar solucionado.

**Comment by joao-felipe-goncalves** [comment]
Sim, acabei não dando commit.

**Comment by joao-felipe-goncalves** [comment]
Encerrado!
