### ISSUE TITLE
Implementar mutação

### ISSUE THREAD

**Issue by joao-felipe-goncalves** [Ailtonjr/AG-Caixeiro-Viajante#9]
Implementar mutação.
Randomizar dois index antes de inserir o ultimo como primeiro.
1 2 3 4 1

1 2 3 4
    ^    ^
1 4 3 2

Final: 1 4 3 2 1

**Comment by Ailtonjr** [comment]
Resolvido! https://github.com/Ailtonjr/AG-Caixeiro-Viajante/commit/465b104df25e49a8aa53a7544a78347e1a240e74
